


export const ARR_ACTION_TO_OMIT_FOR_LOG: string[] = [
  'UPDATE_USER_FOOTPRINT',
  'CLOSE_MODAL_THANK_YOU', 'SEND_COMMENT_FORM',
  'SAVE_USER_VISIT_ACTIONS_REQUEST',
  'START_USER_SESSION_REQUEST', 'UPLOAD_TREE_DATA',
  'CLOSE_ALL_MODALS', 'PRESS_OK_IN_SELECT_ROLE' ]